### ISSUE TITLE
バックエンドのテストを書くべき

### ISSUE THREAD

**Issue by toku-sa-n** [givery-bootcamp/dena-2024-team6#15]

**Comment by funobu** [comment]
単体テスト欲しいですね！✨

あったら嬉しい単体テストが

1. Controller層：入力データによってちゃんとエラーハンドリングできてるかを担保する
2. Repository層：DBから正しくデータを取得できるか担保する

の2つだと思っているのだけど、現状のコード構成だとそれらを書くのが難しそう。
少しリファクタリングする必要もあるかもしれない...🤔

**Comment by funobu** [comment]
まだ議論してないのでクローズします
