### ISSUE TITLE
投稿をマークダウン対応する

### ISSUE THREAD

**Issue by funobu** [givery-bootcamp/dena-2024-team6#47]
https://github.com/givery-bootcamp/training-app-2024/issues/32

**Comment by hibalikuhina** [comment]
@funobu 
これは完了した認識で正しい？

**Comment by funobu** [comment]
まだ終わってないはず。
新規作成はできたけど、作成した投稿を詳細画面で表示する際にマークダウン対応できてないんじゃないかな？
